import 'package:hive/hive.dart';
part 'notes_model.g.dart'; // g stand for generated file, this file will be generated by running the command: flutter packages pub run build_runner build
@HiveType(typeId: 0)
class NotesModel{
  @HiveField(0)
  String title;
  @HiveField(1)
  String description;
  NotesModel({required this.title, required this.description});
}


@HiveType(typeId: 1)
class ContactModel{
  String title;
  String description;
  ContactModel({required this.title, required this.description});
}